### ISSUE TITLE
エラー画面の作成

### ISSUE THREAD

**Issue by matsumo1001** [TEAM-SAT/tabinotane#20]
デフォルトのエラー画面を変更する。

**Comment by matsumo1001** [comment]
下記ファイルを修正
/public/500.html（InternalServerErrorの場合）
/public/404.html（URLが存在しない場合）

@sshamoto san
instagramで写真が無いときにでる鳥の画像とかどうでしょうか？twitterのクジラみたいな扱いで。

**Comment by sshamoto** [comment]
了解です。鳥になんか言わせますね。
